import type { GlobalCardNetwork, GlobalCardStyleConfig } from "./payment-card.types";

export const NETWORK_STYLE_MAP: Record<GlobalCardNetwork, Omit<GlobalCardStyleConfig, "logo">> = {
  visa: {
    network: "visa",
    displayName: "Visa",
    gradient: "bg-gradient-to-br from-[#0c1f3d] via-[#102a54] to-[#1a3d6d]",
    glow: "from-blue-500/20 via-sky-400/10 to-transparent",
    tier: "SIGNATURE",
    textColor: "text-white",
    hologramColor: "bg-gradient-to-tr from-cyan-400 via-sky-300 to-indigo-400",
  },
  mastercard: {
    network: "mastercard",
    displayName: "Mastercard",
    gradient: "bg-gradient-to-br from-[#121214] via-[#1c1c20] to-[#26262b]",
    glow: "from-rose-500/20 via-amber-400/15 to-transparent",
    tier: "WORLD ELITE",
    textColor: "text-white",
    hologramColor: "bg-gradient-to-tr from-amber-400 via-rose-400 to-yellow-300",
  },
  "american-express": {
    network: "american-express",
    displayName: "American Express",
    gradient: "bg-gradient-to-br from-[#1e293b] via-[#334155] to-[#1e293b]",
    glow: "from-slate-400/25 via-slate-200/15 to-transparent",
    tier: "CENTURION",
    textColor: "text-slate-100",
    hologramColor: "bg-gradient-to-tr from-slate-300 via-cyan-200 to-slate-400",
  },
  rupay: {
    network: "rupay",
    displayName: "RuPay",
    gradient: "bg-gradient-to-br from-[#0a1c38] via-[#0f2c4f] to-[#0c4a52]",
    glow: "from-amber-500/20 via-emerald-500/20 to-transparent",
    tier: "SELECT",
    textColor: "text-white",
    hologramColor: "bg-gradient-to-tr from-orange-400 via-emerald-300 to-cyan-400",
  },
  discover: {
    network: "discover",
    displayName: "Discover",
    gradient: "bg-gradient-to-br from-[#1c1917] via-[#292524] to-[#431407]",
    glow: "from-orange-500/25 via-amber-500/15 to-transparent",
    tier: "CASHBACK",
    textColor: "text-white",
    hologramColor: "bg-gradient-to-tr from-orange-400 via-amber-300 to-yellow-200",
  },
  "diners-club": {
    network: "diners-club",
    displayName: "Diners Club",
    gradient: "bg-gradient-to-br from-[#0f172a] via-[#1e293b] to-[#172554]",
    glow: "from-blue-600/20 via-cyan-400/15 to-transparent",
    tier: "PREMIER",
    textColor: "text-white",
    hologramColor: "bg-gradient-to-tr from-sky-400 via-blue-300 to-indigo-400",
  },
  jcb: {
    network: "jcb",
    displayName: "JCB",
    gradient: "bg-gradient-to-br from-[#022c22] via-[#064e3b] to-[#0f172a]",
    glow: "from-emerald-500/20 via-teal-400/15 to-transparent",
    tier: "PLATINUM",
    textColor: "text-white",
    hologramColor: "bg-gradient-to-tr from-emerald-400 via-cyan-300 to-yellow-300",
  },
  unionpay: {
    network: "unionpay",
    displayName: "UnionPay",
    gradient: "bg-gradient-to-br from-[#450a0a] via-[#7f1d1d] to-[#1e1b4b]",
    glow: "from-red-500/20 via-amber-400/15 to-transparent",
    tier: "DIAMOND",
    textColor: "text-white",
    hologramColor: "bg-gradient-to-tr from-red-400 via-amber-300 to-yellow-400",
  },
  maestro: {
    network: "maestro",
    displayName: "Maestro",
    gradient: "bg-gradient-to-br from-[#082f49] via-[#0369a1] to-[#082f49]",
    glow: "from-blue-500/20 via-sky-400/15 to-transparent",
    tier: "INTERNATIONAL",
    textColor: "text-white",
    hologramColor: "bg-gradient-to-tr from-sky-300 via-blue-400 to-indigo-300",
  },
  elo: {
    network: "elo",
    displayName: "Elo",
    gradient: "bg-gradient-to-br from-[#18181b] via-[#27272a] to-[#18181b]",
    glow: "from-amber-500/20 via-red-500/15 to-transparent",
    tier: "NANQUIM",
    textColor: "text-white",
    hologramColor: "bg-gradient-to-tr from-yellow-400 via-amber-300 to-rose-400",
  },
  mir: {
    network: "mir",
    displayName: "Mir",
    gradient: "bg-gradient-to-br from-[#064e3b] via-[#047857] to-[#022c22]",
    glow: "from-emerald-500/25 via-green-400/15 to-transparent",
    tier: "SUPREME",
    textColor: "text-white",
    hologramColor: "bg-gradient-to-tr from-emerald-400 via-teal-300 to-green-400",
  },
  hipercard: {
    network: "hipercard",
    displayName: "Hipercard",
    gradient: "bg-gradient-to-br from-[#450a0a] via-[#5c0b0b] to-[#1c1917]",
    glow: "from-red-500/20 via-orange-400/10 to-transparent",
    tier: "PREMIUM",
    textColor: "text-white",
    hologramColor: "bg-gradient-to-tr from-red-400 via-amber-300 to-orange-300",
  },
  troy: {
    network: "troy",
    displayName: "Troy",
    gradient: "bg-gradient-to-br from-[#0f172a] via-[#1e293b] to-[#334155]",
    glow: "from-blue-500/20 via-slate-400/10 to-transparent",
    tier: "SIGNATURE",
    textColor: "text-white",
    hologramColor: "bg-gradient-to-tr from-blue-400 via-sky-300 to-indigo-300",
  },
  verve: {
    network: "verve",
    displayName: "Verve",
    gradient: "bg-gradient-to-br from-[#14532d] via-[#166534] to-[#0f172a]",
    glow: "from-emerald-500/20 via-green-400/10 to-transparent",
    tier: "CLASSIC",
    textColor: "text-white",
    hologramColor: "bg-gradient-to-tr from-emerald-400 via-lime-300 to-teal-300",
  },
  generic: {
    network: "generic",
    displayName: "Card",
    gradient: "bg-gradient-to-br from-[#0f172a] via-[#1e293b] to-[#020617]",
    glow: "from-slate-400/20 via-slate-300/10 to-transparent",
    tier: "INTERNATIONAL",
    textColor: "text-white",
    hologramColor: "bg-gradient-to-tr from-slate-300 via-cyan-200 to-slate-400",
  },
};
